pipeline:
  name: Build harness-gitops-workshop
  identifier: Build_kishore2805_harness_gitops_workshop_1727627211739
  projectIdentifier: Dev
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run with Test
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: account.harnessImage
                    image: golang
                    shell: Sh
                    command: |-
                      set -e

                      # build the docker file
                      GIT_COMMIT=$(git rev-list -1 HEAD) && \
                      DOCKER_BUILDKIT=1 docker build --tag test/podinfo --build-arg "REVISION=${GIT_COMMIT}" .
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "*.xml"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: kishore2805/harness-gitops-workshop
        build: <+input>
